sudo: required
services:
  - docker

before_install:
  - docker build -t dreamaboutme/docker-react -f Dockerfile.dev .

script:
  - docker run dreamaboutme/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-321692277928"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"